language: python
python:
  - "3.8"
# stuff to do before executing the script
before_script:
    # command to install dependencies
  - pip install -r requirements.txt
branches:
  only:
      - staging
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below