language: python
python:
  - "3.8"


branches:
  only:
      - staging

# stuff to do before executing the script
before_script:
    # command to install dependencies
  - pip install -r requirements.txt


services:
    - postgresql


env: DJANGO_SETTINGS_MODULE="config.settings.travis"


# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below